<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>The R Companion to STATS2 - 1&nbsp; Simple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02_inference_for_simple_linear_regression.html" rel="next">
<link href="./index.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./" class="sidebar-logo-link">
      <img src="./STAT2_logo_small.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">The R Companion to STATS2</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Unit A: Linear Regression</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_simple_linear_regression.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_inference_for_simple_linear_regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Inference for Simple Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_multiple_regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_additional_topics_in_regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Additional Topics in Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-simple-linear-regression-model" id="toc-the-simple-linear-regression-model" class="nav-link active" data-scroll-target="#the-simple-linear-regression-model"> <span class="header-section-number">1.1</span> The Simple Linear Regression Model</a>
  <ul class="collapse">
  <li><a href="#exploring-the-accordprice-data-set" id="toc-exploring-the-accordprice-data-set" class="nav-link" data-scroll-target="#exploring-the-accordprice-data-set"> <span class="header-section-number">1.1.1</span> Exploring the <code>AccordPrice</code> data set</a></li>
  <li><a href="#modeling-the-mileage-vs.-price-relationsip" id="toc-modeling-the-mileage-vs.-price-relationsip" class="nav-link" data-scroll-target="#modeling-the-mileage-vs.-price-relationsip"> <span class="header-section-number">1.1.2</span> Modeling the <code>Mileage</code> vs.&nbsp;<code>Price</code> relationsip</a></li>
  <li><a href="#fitting-a-simple-linear-regression-model" id="toc-fitting-a-simple-linear-regression-model" class="nav-link" data-scroll-target="#fitting-a-simple-linear-regression-model"> <span class="header-section-number">1.1.3</span> Fitting a simple linear regression model</a></li>
  <li><a href="#reporting-the-regression-table" id="toc-reporting-the-regression-table" class="nav-link" data-scroll-target="#reporting-the-regression-table"> <span class="header-section-number">1.1.4</span> Reporting the regression table</a></li>
  <li><a href="#reporting-the-anova-table" id="toc-reporting-the-anova-table" class="nav-link" data-scroll-target="#reporting-the-anova-table"> <span class="header-section-number">1.1.5</span> Reporting the ANOVA table</a></li>
  <li><a href="#adding-the-regression-line-to-a-scatterplot" id="toc-adding-the-regression-line-to-a-scatterplot" class="nav-link" data-scroll-target="#adding-the-regression-line-to-a-scatterplot"> <span class="header-section-number">1.1.6</span> Adding the regression line to a scatterplot</a></li>
  <li><a href="#residual-errors" id="toc-residual-errors" class="nav-link" data-scroll-target="#residual-errors"> <span class="header-section-number">1.1.7</span> Residual Errors</a></li>
  <li><a href="#sec-centering-the-mileage-variable" id="toc-sec-centering-the-mileage-variable" class="nav-link" data-scroll-target="#sec-centering-the-mileage-variable"> <span class="header-section-number">1.1.8</span> Centering the Mileage Variable</a></li>
  <li><a href="#displaying-the-fitted-model-equation" id="toc-displaying-the-fitted-model-equation" class="nav-link" data-scroll-target="#displaying-the-fitted-model-equation"> <span class="header-section-number">1.1.9</span> Displaying the fitted model equation</a></li>
  </ul></li>
  <li><a href="#conditions-for-a-simple-linear-model" id="toc-conditions-for-a-simple-linear-model" class="nav-link" data-scroll-target="#conditions-for-a-simple-linear-model"> <span class="header-section-number">1.2</span> Conditions for a Simple Linear Model</a></li>
  <li><a href="#assessing-conditions" id="toc-assessing-conditions" class="nav-link" data-scroll-target="#assessing-conditions"> <span class="header-section-number">1.3</span> Assessing Conditions</a>
  <ul class="collapse">
  <li><a href="#checking-linearity-with-a-fitted-vs.-residuals-plot" id="toc-checking-linearity-with-a-fitted-vs.-residuals-plot" class="nav-link" data-scroll-target="#checking-linearity-with-a-fitted-vs.-residuals-plot"> <span class="header-section-number">1.3.1</span> Checking Linearity with a Fitted vs.&nbsp;Residuals plot</a></li>
  <li><a href="#checking-homogeneity-of-variance-with-a-fitted-vs.-residuals-plot" id="toc-checking-homogeneity-of-variance-with-a-fitted-vs.-residuals-plot" class="nav-link" data-scroll-target="#checking-homogeneity-of-variance-with-a-fitted-vs.-residuals-plot"> <span class="header-section-number">1.3.2</span> Checking Homogeneity of Variance with a Fitted vs.&nbsp;Residuals plot</a></li>
  <li><a href="#checking-normality-with-a-normal-quantile-plot" id="toc-checking-normality-with-a-normal-quantile-plot" class="nav-link" data-scroll-target="#checking-normality-with-a-normal-quantile-plot"> <span class="header-section-number">1.3.3</span> Checking Normality with a Normal-Quantile plot</a></li>
  </ul></li>
  <li><a href="#transformationsreexpressions" id="toc-transformationsreexpressions" class="nav-link" data-scroll-target="#transformationsreexpressions"> <span class="header-section-number">1.4</span> Transformations/Reexpressions</a>
  <ul class="collapse">
  <li><a href="#visualizing-transformed-models" id="toc-visualizing-transformed-models" class="nav-link" data-scroll-target="#visualizing-transformed-models"> <span class="header-section-number">1.4.1</span> Visualizing Transformed Models</a></li>
  <li><a href="#log-transformed-outcome-variables" id="toc-log-transformed-outcome-variables" class="nav-link" data-scroll-target="#log-transformed-outcome-variables"> <span class="header-section-number">1.4.2</span> Log-Transformed Outcome Variables</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="the-simple-linear-regression-model" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="the-simple-linear-regression-model"><span class="header-section-number">1.1</span> The Simple Linear Regression Model</h2>
<p>Linear regression is introduced in Chapter 1 with the motivating question:</p>
<blockquote class="blockquote">
<p>How much should you expect to pay for a used Honda Accord, if you know how many miles the car has already been driven?</p>
</blockquote>
<p>and introduces the <code>AccordPrice</code> data set, which contains information about the list price and mileage for a sample of 30 Honda Accords. The <code>AccordPrice</code> data set is included with the <code>Stat2Data</code> R package, so to access the data for yourself, you’ll need to install the package. If you don’t already know how to install R packages, here are two good resources to walk you through the process:</p>
<ul>
<li>Reading: <a href="https://moderndive.com/1-getting-started.html#package-installation">ModernDive Chapter 1.3.1: Installing Packages</a></li>
<li>Watching: <a href="https://www.youtube.com/watch?v=-wTcDqJWSzA">How to Install Packages in R Studio</a> on YouTube</li>
</ul>
<p>Once you have the package installed, load the package into your R session using:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To load the <code>AccordPrice</code> data set into your R environment, use the command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"AccordPrice"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Age"],"name":[1],"type":["int"],"align":["right"]},{"label":["Price"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mileage"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"7","2":"12.0","3":"74.9"},{"1":"4","2":"17.9","3":"53.0"},{"1":"4","2":"15.7","3":"79.1"},{"1":"7","2":"12.5","3":"50.1"},{"1":"9","2":"9.5","3":"62.0"},{"1":"1","2":"21.5","3":"4.8"},{"1":"18","2":"3.5","3":"89.4"},{"1":"2","2":"22.8","3":"20.8"},{"1":"2","2":"26.8","3":"4.8"},{"1":"5","2":"13.6","3":"48.3"},{"1":"2","2":"19.4","3":"46.5"},{"1":"2","2":"19.5","3":"3.0"},{"1":"6","2":"9.0","3":"64.1"},{"1":"3","2":"17.4","3":"8.3"},{"1":"3","2":"17.8","3":"27.1"},{"1":"2","2":"17.5","3":"20.3"},{"1":"4","2":"13.5","3":"68.4"},{"1":"14","2":"7.0","3":"86.9"},{"1":"9","2":"11.6","3":"64.5"},{"1":"10","2":"7.9","3":"150.5"},{"1":"5","2":"11.7","3":"65.2"},{"1":"3","2":"15.6","3":"56.1"},{"1":"12","2":"5.0","3":"139.4"},{"1":"3","2":"21.0","3":"13.9"},{"1":"4","2":"15.6","3":"18.6"},{"1":"2","2":"17.0","3":"15.7"},{"1":"3","2":"16.0","3":"38.5"},{"1":"3","2":"17.6","3":"19.8"},{"1":"11","2":"6.9","3":"119.3"},{"1":"13","2":"5.5","3":"122.5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>As a side note: not much information is given in the text about how this sample of 30 Accords was collected, but we can gather a bit more information by looking at the help page for the <code>AccordPrice</code> data set. To open the help page for the <code>AccordPrice</code> data set, you can run the command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>?AccordPrice</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>in the R console. By reading the “Details” and “Source” sections, we can learn that these 30 Accords were listed for sale on Cars.com in Lakewood Ohio during February 2017. Whenever you want to to know more about one of the textbook’s data sets, the help page for that data set is a good place to look first. Sometimes there’s not much more information than given in the textbook, but every little bit helps!</p>
<section id="exploring-the-accordprice-data-set" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="exploring-the-accordprice-data-set"><span class="header-section-number">1.1.1</span> Exploring the <code>AccordPrice</code> data set</h3>
<p>Figure 1.2 displays a scatter plot of the <code>Mileage</code> and <code>Price</code> variable, showing how those variables relate to one another. To re-produce this scatter plot, we’ll use the <code>ggplot2</code> R package <span class="citation" data-cites="ggplot2package">(<a href="references.html#ref-ggplot2package" role="doc-biblioref">Wickham 2016</a>)</span>. If you’re not already familiar with the <code>ggplot2</code> package, here are a few good resources to help you get started:</p>
<ul>
<li>Reading: <a href="https://moderndive.com/2-viz.html">ModernDive Chapter 2: Data Visualization</a></li>
<li>Reading: <a href="https://datasciencebook.ca/viz.html">Effective data visualization</a></li>
<li>Watching: <a href="https://www.youtube.com/watch?v=HPJn1CMvtmI">ggplot for plots and graphs</a> on YouTube</li>
</ul>
<p>To re-create this scatter plot, we’ll map the <code>Mileage</code> variable to x-axis aesthetic, and the <code>Price</code> variable to the y-axis aesthetic, and draw a layer of points to represent each of the 30 cars using <code>geom_point()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> AccordPrice,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>Mileage, <span class="at">y=</span>Price)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>       ) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="01_simple_linear_regression_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout-aside callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Aside
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you want to <strong>exactly</strong> reproduce the scatter plots in STAT2, right down to the colors, backgrounds, and fonts, you can use the following ggplot2 theme:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>theme_stat2 <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">base_size =</span> <span class="dv">11</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">base_family =</span> <span class="st">""</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">base_line_size =</span> base_size<span class="sc">/</span><span class="dv">22</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">base_rect_size =</span> base_size<span class="sc">/</span><span class="dv">22</span>) {</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">%+replace%</span> </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">color=</span><span class="st">"black"</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">color=</span><span class="st">"black"</span>),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background=</span><span class="fu">element_rect</span>(<span class="at">colour=</span><span class="st">"black"</span>),</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">complete =</span> <span class="cn">TRUE</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>And use the hex color code #92278f for your geometric objects. For example, this could <strong>exactly</strong> reproduce Figure 1.2 by adapting the code above to use this new theme:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> AccordPrice,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>Mileage, <span class="at">y=</span>Price)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>       ) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"#92278f"</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_stat2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>In the rest of this book, we <em>won’t</em> use the STAT2 theme for our visualizations, but provide it here for completeness.</p>
</div>
</div>
</section>
<section id="modeling-the-mileage-vs.-price-relationsip" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="modeling-the-mileage-vs.-price-relationsip"><span class="header-section-number">1.1.2</span> Modeling the <code>Mileage</code> vs.&nbsp;<code>Price</code> relationsip</h3>
<p>Example 1.3 shows a summary of a simple linear regression model fit to the <code>Mileage</code> and <code>Price</code> variable in the <code>AccordPrices</code> data set. This summary is actually a mix of two different summaries, a regression table and an Analysis of Variance (ANOVA) table. Reproducing this summary will be a 3 step process in R:</p>
<ol type="1">
<li>Fitting the model using the <code>lm()</code> function</li>
<li>Printing the regression table with the <code>summary()</code> function</li>
<li>Printing the ANOVA table with the <code>anova()</code> function</li>
</ol>
</section>
<section id="fitting-a-simple-linear-regression-model" class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="fitting-a-simple-linear-regression-model"><span class="header-section-number">1.1.3</span> Fitting a simple linear regression model</h3>
<p>The <code>lm()</code> function (short for <strong>l</strong>inear <strong>m</strong>odel) does the “heavy lifting’ of estimating the coefficients of the simple linear model. In other words, the <code>lm()</code> function find the optimal values for <span class="math inline">\(\hat{\beta_0}\)</span> and <span class="math inline">\(\hat{\beta_1}\)</span> in the model <span class="math inline">\(Price = \hat{\beta_0} + \hat{\beta_1} \cdot Mileage + \epsilon\)</span>.</p>
<p>To fit a linear regression model using <code>lm</code>, you need to supply:</p>
<ol type="1">
<li>A formula describing relationship between the outcome and explanatory variable(s)</li>
<li>The name of a data set where the outcome and explanatory variables can be found.</li>
</ol>
<p>In this case, our call to the <code>lm</code> function would be:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>price_mileage_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Mileage, <span class="at">data =</span> AccordPrice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The first argument inside the <code>lm()</code> function is the formula describing the structure of the model. In R, model formulas are always created using the <code>~</code> symbol, with the outcome variable named on the left, and the explanatory variables(s) named on the right. As you might notice, R’s model formula code is an adaptation of how the model is described in mathematical notation.</p>
<p>Also, take note that we’ve saved the results from fitting this linear model in a new R object named <code>price_mileage_model</code>. We’ll need to use this new object to produce the regression table and the ANOVA table in steps 2 and 3 below.</p>
</section>
<section id="reporting-the-regression-table" class="level3" data-number="1.1.4">
<h3 data-number="1.1.4" class="anchored" data-anchor-id="reporting-the-regression-table"><span class="header-section-number">1.1.4</span> Reporting the regression table</h3>
<p>In order to report the regression table, we need to call the <code>summary()</code> function on the linear model object we just created:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>price_mileage_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Mileage, <span class="at">data =</span> AccordPrice)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(price_mileage_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Mileage, data = AccordPrice)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.5984 -1.8169 -0.4148  1.4502  6.5655 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  20.8096     0.9529   21.84  &lt; 2e-16 ***
Mileage      -0.1198     0.0141   -8.50 3.06e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.085 on 28 degrees of freedom
Multiple R-squared:  0.7207,    Adjusted R-squared:  0.7107 
F-statistic: 72.25 on 1 and 28 DF,  p-value: 3.055e-09</code></pre>
</div>
</div>
<p>As we can see, the <code>summary()</code> function first prints out a few things <em>not</em> shown as part of the summary in the textbook: a copy of the code used to fit the model, and a the <a href="https://en.wikipedia.org/wiki/Five-number_summary">Five-number summary</a> of the model’s residual errors. These are followed by the regression table summarizing the intercept and slope, and a “goodness of fit” summary of the model as whole.</p>
</section>
<section id="reporting-the-anova-table" class="level3" data-number="1.1.5">
<h3 data-number="1.1.5" class="anchored" data-anchor-id="reporting-the-anova-table"><span class="header-section-number">1.1.5</span> Reporting the ANOVA table</h3>
<p>The ANOVA table is found by calling the aptly named <code>anova()</code> function on the linear model, the same way we just did with the summary() function a moment ago:</p>
<div class="cell" data-df-print="default">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>price_mileage_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Mileage, <span class="at">data =</span> AccordPrice)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(price_mileage_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Price
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Mileage    1 687.66  687.66  72.253 3.055e-09 ***
Residuals 28 266.49    9.52                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="adding-the-regression-line-to-a-scatterplot" class="level3" data-number="1.1.6">
<h3 data-number="1.1.6" class="anchored" data-anchor-id="adding-the-regression-line-to-a-scatterplot"><span class="header-section-number">1.1.6</span> Adding the regression line to a scatterplot</h3>
<p>Figure 1.3 shows the Price vs.&nbsp;Mileage scatter plot again, but this time with a line representing the regression model’s predictions drawn on top of the raw data. Surprisingly, the easiest method for visualizing the predictions of a regression model <strong>doesn’t</strong> involve the fitted model object. Instead, we will begin with the same ggplot code we used to draw the Mileage vs.&nbsp;Price scatter plot earlier, and add to it. The <code>geom_smooth()</code> function is used to draw the regression line on top of the raw data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> AccordPrice,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Mileage, <span class="at">y =</span> Price)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>       ) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">formula =</span> y<span class="sc">~</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="01_simple_linear_regression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><code>geom_smooth()</code> is a generic smoothing function: the key argument that tells it to fit and display a linear regression model is the <code>method = lm</code> argument. Without the <code>method=lm</code> argument, <code>geom_smooth()</code> will not display a linear model.</p>
<p>The <code>se = FALSE</code> argument is included to stop ggplot from drawing confidence interval bands around the regression line. And, the <code>formula = y~x</code> argument is included simply to prevent ggplot from printing an annoying message that says <span style="font-color=" data-red=""><code><code>geom_smooth()</code> using formula ‘y ~ x’</code></span> when creating the plot.</p>
</section>
<section id="residual-errors" class="level3" data-number="1.1.7">
<h3 data-number="1.1.7" class="anchored" data-anchor-id="residual-errors"><span class="header-section-number">1.1.7</span> Residual Errors</h3>
<p>An important component of any statistical model is the residual error - the difference between the observed value of the outcome variable, and the value your model predicted that outcome to be, based on the same explanatory variable value. No model will predict every observation in your data literally <em>perfectly</em>, and measuring the kinds of errors your model makes is crucial for knowing whether you’ve built a reasonable model of you data.</p>
<p>The residual errors will feature prominently when we <a href="#assessing-conditions">assess the conditions for inference</a> later in this chapter. For now, we’ll just learn how to compute the residual errors around your model predictions, but we won’t <em>do</em> anything more with those values.</p>
<p>The simplest way to compute the difference between observed outcome and predicted outcome for each observation in your data set is to use the <code>residuals()</code> function on your fitted model object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>price_mileage_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Mileage, <span class="at">data =</span> AccordPrice)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(price_mileage_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5          6          7 
 0.1643021  3.4404204  4.3675123 -2.3070342 -3.8812720  1.2654845 -6.5984246 
         8          9         10         11         12         13         14 
 4.4824757  6.5654845 -1.4226957  4.1616428 -0.9501770 -4.1296669 -2.4151737 
        15         16         17         18         19         20         21 
 0.2372910 -0.8774303  0.8855244 -3.3979545 -1.4817422  5.1220854 -1.2978738 
        22         23         24         25         26         27         28 
 1.5118375  0.8921728  1.8557732 -2.9811106 -1.9285653 -0.1968528 -0.8373363 
        29         30 
 0.3839526 -0.6326491 </code></pre>
</div>
</div>
<p>This returns a vector with as many elements as there are rows in your data set, and each element in the vector measures the residual error between model and data for that particular row. For example, the residual error for the Accord price in the first row of the data set was 0.1643021, meaning the model over-predicted it’s price by 0.1643021 thousand dollars (or, 164 dollars).</p>
<p>But, one shortcoming of this function is that the residual errors are separated from the observed outcome values and the predicted outcome values. If you <em>only</em> need the residuals this is not an issue, but more often than the not, you’ll need context to help understand and use the residuals effectively.</p>
<p>The <code>augment()</code> function from the <code>broom()</code> package produces a table that contains the original data the model was fit to, the predicted value for each observation, and the residual error for that observation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>price_mileage_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Mileage, <span class="at">data =</span> AccordPrice)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(price_mileage_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Price"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Mileage"],"name":[2],"type":["dbl"],"align":["right"]},{"label":[".fitted"],"name":[3],"type":["dbl"],"align":["right"]},{"label":[".resid"],"name":[4],"type":["dbl"],"align":["right"]},{"label":[".hat"],"name":[5],"type":["dbl"],"align":["right"]},{"label":[".sigma"],"name":[6],"type":["dbl"],"align":["right"]},{"label":[".cooksd"],"name":[7],"type":["dbl"],"align":["right"]},{"label":[".std.resid"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"12.0","2":"74.9","3":"11.835698","4":"0.1643021","5":"0.04199792","6":"3.141485","7":"6.489773e-05","8":"0.05441255"},{"1":"17.9","2":"53.0","3":"14.459580","4":"3.4404204","5":"0.03338199","6":"3.068622","7":"2.221641e-02","8":"1.13428779"},{"1":"15.7","2":"79.1","3":"11.332488","4":"4.3675123","5":"0.04593859","6":"3.021501","7":"5.057567e-02","8":"1.44938964"},{"1":"12.5","2":"50.1","3":"14.807034","4":"-2.3070342","5":"0.03374238","6":"3.109013","7":"1.010523e-02","8":"-0.76075840"},{"1":"9.5","2":"62.0","3":"13.381272","4":"-3.8812720","5":"0.03449921","6":"3.048295","7":"2.928872e-02","8":"-1.28037430"},{"1":"21.5","2":"4.8","3":"20.234515","4":"1.2654845","5":"0.08495148","6":"3.131318","7":"8.535810e-03","8":"0.42881893"},{"1":"3.5","2":"89.4","3":"10.098425","4":"-6.5984246","5":"0.05872029","6":"2.856013","7":"1.515932e-01","8":"-2.20455072"},{"1":"22.8","2":"20.8","3":"18.317524","4":"4.4824757","5":"0.05707824","6":"3.013429","7":"6.776470e-02","8":"1.49630214"},{"1":"26.8","2":"4.8","3":"20.234515","4":"6.5654845","5":"0.08495148","6":"2.850483","7":"2.297548e-01","8":"2.22476376"},{"1":"13.6","2":"48.3","3":"15.022696","4":"-1.4226957","5":"0.03414268","6":"3.129274","7":"3.891742e-03","8":"-0.46923967"},{"1":"19.4","2":"46.5","3":"15.238357","4":"4.1616428","5":"0.03467825","6":"3.034052","7":"3.386031e-02","8":"1.37299176"},{"1":"19.5","2":"3.0","3":"20.450177","4":"-0.9501770","5":"0.08875605","6":"3.135806","7":"5.069744e-03","8":"-0.32264606"},{"1":"9.0","2":"64.1","3":"13.129667","4":"-4.1296669","5":"0.03524649","6":"3.035665","7":"3.392826e-02","8":"-1.36284362"},{"1":"17.4","2":"8.3","3":"19.815174","4":"-2.4151737","5":"0.07794093","6":"3.104138","7":"2.809268e-02","8":"-0.81528261"},{"1":"17.8","2":"27.1","3":"17.562709","4":"0.2372910","5":"0.04903587","6":"3.141302","7":"1.603970e-04","8":"0.07887481"},{"1":"17.5","2":"20.3","3":"18.377430","4":"-0.8774303","5":"0.05778750","6":"3.136831","7":"2.632751e-03","8":"-0.29300658"},{"1":"13.5","2":"68.4","3":"12.614476","4":"0.8855244","5":"0.03735111","6":"3.136846","7":"1.660417e-03","8":"0.29255382"},{"1":"7.0","2":"86.9","3":"10.397955","4":"-3.3979545","5":"0.05521088","6":"3.068770","7":"3.751789e-02","8":"-1.13315495"},{"1":"11.6","2":"64.5","3":"13.081742","4":"-1.4817422","5":"0.03540970","6":"3.128205","7":"4.389652e-03","8":"-0.48903549"},{"1":"7.9","2":"150.5","3":"2.777915","4":"5.1220854","5":"0.22560924","6":"2.935164","7":"5.185356e-01","8":"1.88671332"},{"1":"11.7","2":"65.2","3":"12.997874","4":"-1.2978738","5":"0.03571140","6":"3.131337","7":"3.398647e-03","8":"-0.42841842"},{"1":"15.6","2":"56.1","3":"14.088163","4":"1.5118375","5":"0.03338501","6":"3.127682","7":"4.290451e-03","8":"0.49844532"},{"1":"5.0","2":"139.4","3":"4.107827","4":"0.8921728","5":"0.18370507","6":"3.135898","7":"1.152851e-02","8":"0.32008447"},{"1":"21.0","2":"13.9","3":"19.144227","4":"1.8557732","5":"0.06778784","6":"3.119799","7":"1.411304e-02","8":"0.62302677"},{"1":"15.6","2":"18.6","3":"18.581111","4":"-2.9811106","5":"0.06027705","6":"3.085403","7":"3.186815e-02","8":"-0.99682141"},{"1":"17.0","2":"15.7","3":"18.928565","4":"-1.9285653","5":"0.06480240","6":"3.118120","7":"1.447776e-02","8":"-0.64643049"},{"1":"16.0","2":"38.5","3":"16.196853","4":"-0.1968528","5":"0.03869513","6":"3.141413","7":"8.524437e-05","8":"-0.06508041"},{"1":"17.6","2":"19.8","3":"18.437336","4":"-0.8373363","5":"0.05850720","6":"3.137258","7":"2.431216e-03","8":"-0.27972455"},{"1":"6.9","2":"119.3","3":"6.516047","4":"0.3839526","5":"0.12091560","6":"3.140662","7":"1.211783e-03","8":"0.13273991"},{"1":"5.5","2":"122.5","3":"6.132649","4":"-0.6326491","5":"0.12978302","6":"3.138939","7":"3.603604e-03","8":"-0.21983069"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The predicted values are in the <code>.fitted</code> columns, and the residual errors are in the <code>.resid</code> column. The output holds many other pieces of information which will become useful in the future, but for now we can ignore the <code>.hat</code>, <code>.sigma</code>, <code>.cooks</code>, <code>.std.resid</code> columns.</p>
</section>
<section id="sec-centering-the-mileage-variable" class="level3" data-number="1.1.8">
<h3 data-number="1.1.8" class="anchored" data-anchor-id="sec-centering-the-mileage-variable"><span class="header-section-number">1.1.8</span> Centering the Mileage Variable</h3>
<p>Example 1.4 demonstrates how centering a variable (i.e., shifting all the values left or right by a single chosen number) changes the interpretation of the intercept coefficient, but not the slope coefficient. In this example, the Mileage variable is shifted to the left by 50; in other words, 50 is subtracted from all the Mileage values <em>before</em> fitting the model.</p>
<p>The easiest way to replicate this model is create a new variable in the <code>AccordPrices</code> data set which holds the centered Mileage values. To make this new column, we’ll use the <code>mutate</code> function from the <code>dplyr</code> package <span class="citation" data-cites="dplyr_package">(<a href="references.html#ref-dplyr_package" role="doc-biblioref">Wickham et al. 2022</a>)</span>. If you aren’t familiar with the <code>mutate()</code> function or the <code>dplyr</code> package, here are a few good resources to investigate:</p>
<ul>
<li>Reading: <a href="https://moderndive.com/3-wrangling.html">ModernDive Chapter 3: Data Wrangling</a></li>
<li>Reading: <a href="https://datasciencebook.ca/wrangling.html">Cleaning and Wrangling Data</a></li>
<li>Watching: <a href="https://www.youtube.com/watch?v=Gvhkp-Yw65U">Dplyr Essentials</a> on YouTube</li>
</ul>
<p>In this case, the ‘mutation’ we apply is quite simple: we just use the subtraction operator to subtract 50, and R automatically applies this subtraction to all 30 values in the Mileage column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>AccordPrice <span class="ot">&lt;-</span> AccordPrice <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Mileage_c50 =</span> Mileage <span class="sc">-</span> <span class="dv">50</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>AccordPrice</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Age"],"name":[1],"type":["int"],"align":["right"]},{"label":["Price"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mileage"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Mileage_c50"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"7","2":"12.0","3":"74.9","4":"24.9"},{"1":"4","2":"17.9","3":"53.0","4":"3.0"},{"1":"4","2":"15.7","3":"79.1","4":"29.1"},{"1":"7","2":"12.5","3":"50.1","4":"0.1"},{"1":"9","2":"9.5","3":"62.0","4":"12.0"},{"1":"1","2":"21.5","3":"4.8","4":"-45.2"},{"1":"18","2":"3.5","3":"89.4","4":"39.4"},{"1":"2","2":"22.8","3":"20.8","4":"-29.2"},{"1":"2","2":"26.8","3":"4.8","4":"-45.2"},{"1":"5","2":"13.6","3":"48.3","4":"-1.7"},{"1":"2","2":"19.4","3":"46.5","4":"-3.5"},{"1":"2","2":"19.5","3":"3.0","4":"-47.0"},{"1":"6","2":"9.0","3":"64.1","4":"14.1"},{"1":"3","2":"17.4","3":"8.3","4":"-41.7"},{"1":"3","2":"17.8","3":"27.1","4":"-22.9"},{"1":"2","2":"17.5","3":"20.3","4":"-29.7"},{"1":"4","2":"13.5","3":"68.4","4":"18.4"},{"1":"14","2":"7.0","3":"86.9","4":"36.9"},{"1":"9","2":"11.6","3":"64.5","4":"14.5"},{"1":"10","2":"7.9","3":"150.5","4":"100.5"},{"1":"5","2":"11.7","3":"65.2","4":"15.2"},{"1":"3","2":"15.6","3":"56.1","4":"6.1"},{"1":"12","2":"5.0","3":"139.4","4":"89.4"},{"1":"3","2":"21.0","3":"13.9","4":"-36.1"},{"1":"4","2":"15.6","3":"18.6","4":"-31.4"},{"1":"2","2":"17.0","3":"15.7","4":"-34.3"},{"1":"3","2":"16.0","3":"38.5","4":"-11.5"},{"1":"3","2":"17.6","3":"19.8","4":"-30.2"},{"1":"11","2":"6.9","3":"119.3","4":"69.3"},{"1":"13","2":"5.5","3":"122.5","4":"72.5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Note that we saved our centered mileage scores in a variable named <code>Mileage_c50</code>, to help us keep track of what these values mean: they are mileage values that have been centered by 50.</p>
<p>From here, we just need to fit another linear model with <code>lm()</code>, using our new <code>Mileage_c50</code> variable as the explanatory variable in our model formula:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>centered_mileage_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Mileage_c50, <span class="at">data =</span> AccordPrice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The textbook only presents the fitted model equation (not the full regression table) in order to show the intercept and slope coefficients. If you ever need <strong>just</strong> the coefficient values, without the rest of the summaries in the regression table, you can use the <code>coef()</code> function on your model object to print them out:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>centered_mileage_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Mileage_c50, <span class="at">data =</span> AccordPrice)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(centered_mileage_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) Mileage_c50 
 14.8190154  -0.1198119 </code></pre>
</div>
</div>
</section>
<section id="displaying-the-fitted-model-equation" class="level3" data-number="1.1.9">
<h3 data-number="1.1.9" class="anchored" data-anchor-id="displaying-the-fitted-model-equation"><span class="header-section-number">1.1.9</span> Displaying the fitted model equation</h3>
<p>If you are using a literate programming environment (like an RMarkdown or Quarto document), you might find yourself wanting to display the fitted model equation in your document, formatted like a “fancy” mathematical equation. You could always write the LaTeX markup you need yourself, but the <a href="https://datalorax.github.io/equatiomatic/">equatiomatic</a> package <span class="citation" data-cites="equatiomatic_package">(<a href="references.html#ref-equatiomatic_package" role="doc-biblioref">Anderson, Heiss, and Sumners 2022</a>)</span> can automatically generate what you need, straight from the model object itself!</p>
<p>To demonstrate, let’s display a formatted equation representing the fitted regression model based on the centered mileage scores by using the <code>extract_eq()</code> function on the model object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(equatiomatic)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>centered_mileage_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Mileage_c50, <span class="at">data =</span> AccordPrice)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_eq</span>(centered_mileage_model, <span class="at">use_coefs =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{Price}} = 14.82 - 0.12(\operatorname{Mileage\_c50})
\]</span></p>
</div>
</div>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>As the time of writing, there are problems with using the equatiomatic package to display equations when rendering Quarto documents to PDF. Thankfully, there is a workaround that is not too difficult, which involves saving the equation as a variable, and <code>cat()</code>-ing the equation yourself:</p>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| results: asis</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>eq <span class="ot">&lt;-</span> <span class="fu">extract_eq</span>(centered_mileage_model, <span class="at">use_coefs =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"$$"</span>, eq, <span class="st">"$$"</span>, <span class="at">sep =</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><span class="math display">\[
\operatorname{\widehat{Price}} = 14.82 - 0.12(\operatorname{Mileage\_c50})
\]</span></p>
<p>Just be sure to set the <code>results: asis</code> chunk option!</p>
</div>
</div>
</section>
</section>
<section id="conditions-for-a-simple-linear-model" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="conditions-for-a-simple-linear-model"><span class="header-section-number">1.2</span> Conditions for a Simple Linear Model</h2>
<p>Section 1.2 introduces mostly conceptual information about neccesary and sufficient conditions for interference on a linear model, but does introduce the formula for estimating the standard error of the regression (also called the “Residual Standard Error”). You’ll rarely need to use this formula “manually”, since the value of this statistic is included in the output from the <code>summary()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>price_mileage_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Mileage, <span class="at">data =</span> AccordPrice)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(price_mileage_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>
Call:
lm(formula = Price ~ Mileage, data = AccordPrice)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.5984 -1.8169 -0.4148  1.4502  6.5655 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  20.8096     0.9529   21.84  &lt; 2e-16 ***
Mileage      -0.1198     0.0141   -8.50 3.06e-09 ***

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

<span style="background-color: pink;">Residual standard error: 3.085 on 28 degrees of freedom</span>
Multiple R-squared:  0.7207,    Adjusted R-squared:  0.7107 
F-statistic: 72.25 on 1 and 28 DF,  p-value: 3.055e-09

</code>
</pre>
<p>If you ever need to obtain this value <em>alone</em> (without the rest of the summary table), you can use the <code>sigma()</code> function on the fitted model object to extract it;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sigma</span>(price_mileage_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.08504</code></pre>
</div>
</div>
</section>
<section id="assessing-conditions" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="assessing-conditions"><span class="header-section-number">1.3</span> Assessing Conditions</h2>
<p>Section 1.4 introduces two type of plots that crucial for assessing the validity of the assumptions underpinning theory-based inference on a regression model:</p>
<ol type="1">
<li>The Fitted vs.&nbsp;Residuals Plot</li>
<li>The Normal Quantile plot (which is a specific type of Quantile-Quantile plot)</li>
</ol>
<p>There are many ways of generating thse plots from a linear model in R, but perhaps the easiest, most full-featured (and prettiest!) method is to use the tools from the <a href="https://easystats.github.io/performance/">performance</a> package <span class="citation" data-cites="performance_package">(<a href="references.html#ref-performance_package" role="doc-biblioref">Lüdecke et al. 2021</a>)</span>.</p>
<p>The <code>check_model()</code> function from the <code>performance</code> package can be used to create both fitted vs.&nbsp;residuals plots, and Normal Quantile plots. What’s more, it can create different variations of fitted vs.&nbsp;residuals plots that are customized to help you check either the Linearity or the Homogeneity of Variance assumptions.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>You’ll also want to install the <code>patchwork</code> and <code>see</code> packages at the same time you install the <code>performance</code> package, as these supplemental packages are very useful for constructing visualiations with the <code>performance</code> package.</p>
</div>
</div>
<section id="checking-linearity-with-a-fitted-vs.-residuals-plot" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="checking-linearity-with-a-fitted-vs.-residuals-plot"><span class="header-section-number">1.3.1</span> Checking Linearity with a Fitted vs.&nbsp;Residuals plot</h3>
<p>To generate a variant of the Fitted vs.&nbsp;Residuals plot designed to help you assess the Linearity assumption, you’ll include the <code>check="linearity"</code> argument to the <code>check_model()</code> function. The <code>panel=FALSE</code> argument instructs the <code>check_model()</code> function to devote the entire plot window to this plot (instead of leaving room for other plots checking other model assumptions).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(see)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>price_mileage_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Mileage, <span class="at">data =</span> AccordPrice)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>linearity_check <span class="ot">&lt;-</span> <span class="fu">check_model</span>(price_mileage_model, <span class="at">check=</span><span class="st">"linearity"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">panel=</span><span class="cn">FALSE</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                              )</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(linearity_check, <span class="at">data=</span>price_mileage_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$NCV</code></pre>
</div>
<div class="cell-output-display">
<p><img src="01_simple_linear_regression_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>One odd thing to note: you need to pass the fitted model object as the data arguemnt to the plot function, <em>not</em> the original data set.</p>
</section>
<section id="checking-homogeneity-of-variance-with-a-fitted-vs.-residuals-plot" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="checking-homogeneity-of-variance-with-a-fitted-vs.-residuals-plot"><span class="header-section-number">1.3.2</span> Checking Homogeneity of Variance with a Fitted vs.&nbsp;Residuals plot</h3>
<p>The only thing that changes for producing a a Fitted vs.&nbsp;Residuals plot designed to check for homoskedasticity (a fancy word for “equal variance”) is writing <code>check="homogeneity"</code> in the <code>check_model()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>variance_check <span class="ot">&lt;-</span> <span class="fu">check_model</span>(price_mileage_model, <span class="at">check=</span><span class="st">"homogeneity"</span>,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">panel=</span><span class="cn">FALSE</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                              )</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(variance_check, <span class="at">data=</span>price_mileage_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$HOMOGENEITY</code></pre>
</div>
<div class="cell-output-display">
<p><img src="01_simple_linear_regression_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="checking-normality-with-a-normal-quantile-plot" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="checking-normality-with-a-normal-quantile-plot"><span class="header-section-number">1.3.3</span> Checking Normality with a Normal-Quantile plot</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>normality_check <span class="ot">&lt;-</span> <span class="fu">check_model</span>(price_mileage_model, <span class="at">check=</span><span class="st">"qq"</span>,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">panel=</span><span class="cn">FALSE</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                              )</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(normality_check, <span class="at">data=</span>price_mileage_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>For confidence bands, please install `qqplotr`.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$QQ</code></pre>
</div>
<div class="cell-output-display">
<p><img src="01_simple_linear_regression_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="transformationsreexpressions" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="transformationsreexpressions"><span class="header-section-number">1.4</span> Transformations/Reexpressions</h2>
<p>Section 1.4 introduces a new data set and new model into the mix, to demonstrate how transformations of the outcome and/or explantory variable may be useful when the conditions for a simple linear regression model are not met.</p>
<p>The <code>CountyHealth</code> data set measures the number of doctors and the number of hospitals from 53 Counties in the United States.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(CountyHealth)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>CountyHealth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["County"],"name":[1],"type":["fct"],"align":["left"]},{"label":["MDs"],"name":[2],"type":["int"],"align":["right"]},{"label":["Hospitals"],"name":[3],"type":["int"],"align":["right"]},{"label":["Beds"],"name":[4],"type":["int"],"align":["right"]}],"data":[{"1":"Bay, FL","2":"351","3":"3","4":"605"},{"1":"Beaufort, NC","2":"95","3":"2","4":"134"},{"1":"Beaver, PA","2":"260","3":"2","4":"567"},{"1":"Bernalillo, NM","2":"2797","3":"11","4":"1435"},{"1":"Bibb, GA","2":"769","3":"5","4":"976"},{"1":"Clinton, PA","2":"42","3":"2","4":"245"},{"1":"Comanche, TX","2":"13","3":"2","4":"33"},{"1":"Concordia, LA","2":"20","3":"2","4":"65"},{"1":"Contra Costa, CA","2":"2981","3":"7","4":"1462"},{"1":"Coos, NH","2":"83","3":"3","4":"100"},{"1":"Crawford, KS","2":"56","3":"2","4":"179"},{"1":"Creek, OK","2":"37","3":"2","4":"42"},{"1":"Dona Ana, NM","2":"320","3":"2","4":"350"},{"1":"Douglas, OR","2":"224","3":"2","4":"202"},{"1":"El Paso, TX","2":"1339","3":"8","4":"1675"},{"1":"Elmore, AL","2":"44","3":"2","4":"109"},{"1":"Escambia, FL","2":"973","3":"3","4":"1280"},{"1":"Fairfield, CT","2":"3686","3":"6","4":"1715"},{"1":"Hamilton, OH","2":"4485","3":"12","4":"3351"},{"1":"Hawaii, HI","2":"383","3":"5","4":"474"},{"1":"Hennepin, MN","2":"5338","3":"9","4":"3261"},{"1":"Jefferson, PA","2":"51","3":"2","4":"106"},{"1":"Kenai Peninsula, AK","2":"81","3":"3","4":"96"},{"1":"Kennebec, ME","2":"379","3":"2","4":"295"},{"1":"Kent, MI","2":"1752","3":"5","4":"1887"},{"1":"Labette, KS","2":"39","3":"2","4":"82"},{"1":"Linn, IA","2":"453","3":"2","4":"805"},{"1":"Linn, OR","2":"159","3":"2","4":"112"},{"1":"Macon, NC","2":"101","3":"2","4":"163"},{"1":"Mercer, PA","2":"217","3":"3","4":"550"},{"1":"Mercer, WV","2":"176","3":"4","4":"537"},{"1":"Monmouth, NJ","2":"2459","3":"6","4":"1463"},{"1":"Montgomery, IL","2":"25","3":"2","4":"151"},{"1":"Montgomery, MS","2":"11","3":"2","4":"44"},{"1":"Nassau, NY","2":"8908","3":"13","4":"5034"},{"1":"New Haven, CT","2":"4497","3":"10","4":"2707"},{"1":"Norfolk, VA","2":"1108","3":"4","4":"1079"},{"1":"Okaloosa, FL","2":"502","3":"3","4":"422"},{"1":"Oneida, NY","2":"611","3":"3","4":"815"},{"1":"Ottawa, MI","2":"355","3":"3","4":"280"},{"1":"Passaic, NJ","2":"1145","3":"5","4":"1403"},{"1":"Pawnee, OK","2":"5","3":"2","4":"37"},{"1":"Pecos, TX","2":"9","3":"2","4":"36"},{"1":"Queens, NY","2":"6224","3":"11","4":"4918"},{"1":"Richland, SC","2":"1540","3":"4","4":"1389"},{"1":"Richmond, NC","2":"50","3":"2","4":"205"},{"1":"Sandusky, OH","2":"55","3":"2","4":"304"},{"1":"Sedgwick, KS","2":"1387","3":"7","4":"1607"},{"1":"Sheboygan, WI","2":"205","3":"2","4":"311"},{"1":"Walla Walla, WA","2":"219","3":"2","4":"145"},{"1":"Weber, UT","2":"394","3":"2","4":"466"},{"1":"Whiteside, IL","2":"75","3":"2","4":"188"},{"1":"Windham, CT","2":"160","3":"2","4":"147"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Example 1.7 explores a simple linear model which casts the number doctors in the county as a function of how many hospitals are in the county. However, when we fit this model, we see that not all the conditions for inference seem reasonable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>doctor_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(MDs <span class="sc">~</span> Hospitals, <span class="at">data =</span> CountyHealth)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_eq</span>(doctor_model, <span class="at">use_coefs =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{MDs}} = -1120.56 + 557.32(\operatorname{Hospitals})
\]</span></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CountyHealth, <span class="fu">aes</span>(<span class="at">x=</span>Hospitals, <span class="at">y=</span> MDs)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">formula=</span>y<span class="sc">~</span>x) <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">8000</span>,<span class="at">by=</span><span class="dv">2000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="01_simple_linear_regression_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(doctor_model, <span class="at">check=</span><span class="fu">c</span>(<span class="st">"homogeneity"</span>, <span class="st">"qq"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="01_simple_linear_regression_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The residual errors around this model’s predictions grow larger and more variable as the number of hospitals increases, and they don’t follow a Normal distribution. But, modeling the <strong>square root</strong> of the number of doctor’s alleviates these problems.</p>
<p>There are several ways you can adjust to modeling the square root ofa variable. One method is to make a new variable in the data set that holds the transformed values, following the process we did in <a href="#sec-centering-the-mileage-variable"><span>Section&nbsp;1.1.8</span></a> (where we used the <code>mutate()</code> function to help center the Mileage variable).</p>
<p>Another method is to apply the transformation <em>within the model formula itself</em>! We can apply the <code>sqrt()</code> function to the <code>MDs</code> variable at the same time fit the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>sqrt_doctor_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(MDs) <span class="sc">~</span> Hospitals, <span class="at">data =</span> CountyHealth)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(sqrt_doctor_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)   Hospitals 
  -2.753326    6.876364 </code></pre>
</div>
</div>
<p>One advantage of doing the transformation directly in the model formula is that the <code>extract_eq()</code> function is able to detect the transformation, and include it in the equation!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_eq</span>(sqrt_doctor_model, <span class="at">use_coefs =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{sqrt(MDs)}} = -2.75 + 6.88(\operatorname{Hospitals})
\]</span></p>
</div>
</div>
<p>The diagnostics plots based on the model using the <span class="math inline">\(\sqrt{MDs}\)</span> variable indicate that the Normality assumption is met, and the Equal Variance is much more tenable on the transformed scale:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>sqrt_doctor_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(MDs) <span class="sc">~</span> Hospitals, <span class="at">data =</span> CountyHealth)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(sqrt_doctor_model, <span class="at">check=</span><span class="fu">c</span>(<span class="st">"homogeneity"</span>, <span class="st">"qq"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="01_simple_linear_regression_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="visualizing-transformed-models" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="visualizing-transformed-models"><span class="header-section-number">1.4.1</span> Visualizing Transformed Models</h3>
<p>Often times when an assumption is violated, we may decide to <em>fit</em> the model on a transformed scale, but visualize the model’s predictions on the original scale (since the original scale is more interpretable than say, the square-root scale).</p>
<p>The easiest way to do this when plotting with ggplot and geom_smooth() is to use a square root scale transformation, following by a coordinate transformation that squares the y-axis values (thus reversing the square root operation). What makes this work is that the scale transformation occurs first, so geom_smooth() fits and draws the model on the transformed (and linear!) scale, and coordinate transformation follows, so the model’s predictions are <em>presented</em> on the “raw” scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CountyHealth, <span class="fu">aes</span>(<span class="at">x=</span>Hospitals, <span class="at">y=</span> MDs)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">formula=</span>y<span class="sc">~</span>x) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_sqrt</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">8000</span>,<span class="at">by=</span><span class="dv">2000</span>), <span class="at">expand=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_trans</span>(<span class="at">y =</span> scales<span class="sc">::</span><span class="fu">trans_new</span>(<span class="st">"square"</span>, <span class="cf">function</span>(x) x<span class="sc">^</span><span class="dv">2</span>, <span class="st">"sqrt"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="01_simple_linear_regression_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Another approach is to manually compute a grid of predictions for each x-axis position using the fitted model equation, then square and plot each predicted value. Though not demonstrated with transformations specifically, this type of approach is demonstrated in Chapter 2, when <a href="02_inference_for_simple_linear_regression.html#intervals-for-predictions">plotting prediction intervals</a>.</p>
</section>
<section id="log-transformed-outcome-variables" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="log-transformed-outcome-variables"><span class="header-section-number">1.4.2</span> Log-Transformed Outcome Variables</h3>
<p>All the previous techniques for modeling and visualizing the square-root of an outcome variable applicable to modeling with variables that have been transformed with the logarithmic function as well: we just use the <code>log()</code> function instead of the <code>sqrt()</code> function!</p>
<p>As an example, we can reproduce the fitted model, predictions and visualizations from Example 1.8, where the logarithm of the number of mammal species from 13 islands in Southeast Asia is modeled using the logarithm of the Area of the island as an explanatory variable. Since both variables have been transformed, this type of model is know as a “log-log model”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"SpeciesArea"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>SpeciesArea</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Name"],"name":[1],"type":["fct"],"align":["left"]},{"label":["Area"],"name":[2],"type":["int"],"align":["right"]},{"label":["Species"],"name":[3],"type":["int"],"align":["right"]},{"label":["logArea"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["logSpecies"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"Borneo","2":"743244","3":"129","4":"13.51880","5":"4.85981"},{"1":"Sumatra","2":"473607","3":"126","4":"13.06810","5":"4.83628"},{"1":"Java","2":"125628","3":"78","4":"11.74110","5":"4.35671"},{"1":"Bangka","2":"11964","3":"38","4":"9.38966","5":"3.63759"},{"1":"Bunguran","2":"1594","3":"24","4":"7.37400","5":"3.17805"},{"1":"Banggi","2":"450","3":"18","4":"6.10925","5":"2.89037"},{"1":"Jemaja","2":"194","3":"15","4":"5.26786","5":"2.70805"},{"1":"Karimata Besar","2":"130","3":"19","4":"4.86753","5":"2.94444"},{"1":"Tioman","2":"114","3":"23","4":"4.73620","5":"3.13549"},{"1":"Siantan","2":"113","3":"16","4":"4.72739","5":"2.77259"},{"1":"Sirhassan","2":"46","3":"16","4":"3.82864","5":"2.77259"},{"1":"Redang","2":"25","3":"8","4":"3.21888","5":"2.07944"},{"1":"Penebangan","2":"13","3":"13","4":"2.56495","5":"2.56495"},{"1":"Perhentian Besar","2":"8","3":"6","4":"2.07944","5":"1.79176"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>log_species_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Species) <span class="sc">~</span> <span class="fu">log</span>(Area), <span class="at">data =</span> SpeciesArea)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_eq</span>(log_species_model, <span class="at">use_coefs =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><span class="math display">\[
\operatorname{\widehat{log(Species)}} = 1.62 + 0.24(\operatorname{\log(Area)})
\]</span></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SpeciesArea, <span class="fu">aes</span>(<span class="at">x =</span> Area, <span class="at">y =</span> Species)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">formula=</span>y<span class="sc">~</span>x) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">"log"</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">trans =</span> <span class="st">"log"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="01_simple_linear_regression_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Reproduces Figure 1.19(b), but uses axis labels on the raw instead of logarithmic scale</figcaption><p></p>
</figure>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-equatiomatic_package" class="csl-entry" role="doc-biblioentry">
Anderson, Daniel, Andrew Heiss, and Jay Sumners. 2022. <em>Equatiomatic: Transform Models into ’LaTeX’ Equations</em>. <a href="https://CRAN.R-project.org/package=equatiomatic">https://CRAN.R-project.org/package=equatiomatic</a>.
</div>
<div id="ref-performance_package" class="csl-entry" role="doc-biblioentry">
Lüdecke, Daniel, Mattan S. Ben-Shachar, Indrajeet Patil, Philip Waggoner, and Dominique Makowski. 2021. <span>“<span class="nocase">performance</span>: An <span>R</span> Package for Assessment, Comparison and Testing of Statistical Models.”</span> <em>Journal of Open Source Software</em> 6 (60): 3139. <a href="https://doi.org/10.21105/joss.03139">https://doi.org/10.21105/joss.03139</a>.
</div>
<div id="ref-ggplot2package" class="csl-entry" role="doc-biblioentry">
Wickham, Hadley. 2016. <em>Ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
<div id="ref-dplyr_package" class="csl-entry" role="doc-biblioentry">
Wickham, Hadley, Romain François, Lionel Henry, and Kirill Müller. 2022. <em>Dplyr: A Grammar of Data Manipulation</em>. <a href="https://CRAN.R-project.org/package=dplyr">https://CRAN.R-project.org/package=dplyr</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./02_inference_for_simple_linear_regression.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Inference for Simple Linear Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>