project:
  type: book

book:
  title: "The R Companion to STATS2"
  sidebar: 
    logo: STAT2_logo_small.png
  favicon: favicon.png
  author: "Will Hopper"
  date: "08/18/2020"
  chapters:
    - index.qmd
    - part: "Unit A: Linear Regression"
      chapters:
        - "01_simple_linear_regression.qmd"
        - "02_inference_for_simple_linear_regression.qmd"
        - "03_multiple_regression.qmd"
        - "04_additional_topics_in_regression.qmd"
    - part: "Unit B: Analysis of Variance"
      chapters: 
        - "05_one-way_ANOVA.qmd"
        - "06_two-way_ANOVA.qmd"
        - "07_ANOVA_with_interaction.qmd"
        - "08_additional_topics_in_ANOVA.qmd"
    - part: "Unit C: Logistic Regression"
      chapters:
        - "09_logistic_regression.qmd"
        - "10_multiple_logistic_regression.qmd"
    - references.qmd
    - errata.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: paged
knitr:
  opts_chunk: 
    message: false
