project:
  type: book

book:
  title: "The R Companion to STATS2"
  logo: STAT2_logo_small.png
  favicon: favicon.png
  author: "Will Hopper"
  date: "08/18/2020"
  chapters:
    - index.qmd
    - part: "Unit A: Linear Regression"
      chapters:
        - "01_simple_linear_regression.qmd"
        - "02_inference_for_simple_linear_regression.qmd"
        - "03_multiple_regression.qmd"
        - "04_additional_topics_in_regression.qmd"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: paged
